### ISSUE TITLE
dll not found exception in latest Unity

### ISSUE THREAD

**Issue by vibber** [keijiro/Funnel#16] opened 2018-02-26 09:39 UTC
I try to build a vanilla project where I simply added Funnel to a camera. 
Mac os 10.12.6
Unity 2017.3.1f1

I get a dllnotfound Exception.
![skaermbillede 2018-02-26 kl 10 30 44](https://user-images.githubusercontent.com/4029429/36663253-4b700b9e-1ae1-11e8-9734-9dea08ea16f6.png)

**Comment by robspaull** [comment] 2018-03-19 13:05
Hi, Anyone found a fix for this? Just complied my project and got this same error - project is supposed to go live in a week! Yikes!!

**Comment by keijiro** [comment] 2018-03-19 13:33
Please make sure that "Auto Graphics API for Mac" in the player settings is disabled and OpenGL is explicitly selected.

**Comment by vibber** [comment] 2018-03-19 16:30
Nope, that does not solve the DLLNotFoundException. Testing on a clean
project. Syphon works in editor play mode.

**Comment by robspaull** [comment] 2018-03-20 10:16
Not working for me either :( Just get flashing red screen and errors the console in a dev build. Is it possible to manually place the DLL somewhere?

**Comment by ioannismihailidis** [comment] 2018-03-28 10:02
Same error here.

By putting the funnel binary from funnel.bundle/Contents/MacOS into MyApp.app/Contents/Frameworks/MonoEmbedRuntime/osx the not found error is gone. BUT no Syphon server comes up :(

**Comment by ioannismihailidis** [comment] 2018-03-29 12:06
Finally its running in Unity 2017.1.3f1. Will test it in the current version asap.

The Funnel bundle is build in x64 only , so your app has to be deployed only for x64 platforms AND the bundle needs the right settings for your standalone app:

![ohne titel](https://user-images.githubusercontent.com/1242010/38087915-496b8d1e-335a-11e8-8b77-dbde895371e7.png)

![pluginsettings](https://user-images.githubusercontent.com/1242010/38087925-4e424e22-335a-11e8-8085-18ca0517610d.png)

**Comment by vibber** [comment] 2018-04-03 11:07
I am still waiting for a solution in latest Unity (2017.3.1f1).

**Comment by ioannismihailidis** [comment] 2018-04-03 11:43
@vibber have you seen my post update?

**Comment by vibber** [comment] 2018-04-03 11:48
I see. Any chance you could make the binary available somewhere? I’m a noob
when it comes to compiling.

-Vibeke

**Comment by ioannismihailidis** [comment] 2018-04-03 11:52
[Funnel.bundle.zip](https://github.com/keijiro/Funnel/files/1871332/Funnel.bundle.zip)

here you go. Just extract and exchange the .bundle with the one in the funnel/Plugins folder.

**Comment by vibber** [comment] 2018-04-03 12:18
I still get the dllNotFoundException in Unity 2017.3.1f1. I can't find 2017.4 anywhere so I don't know if that would work.

**Comment by keijiro** [comment] 2018-04-10 07:35
Sorry for not responding earlier. Although the root cause of the problem is still not clear, I've managed to fix the dllNotFoundException problem by updating the .meta file of the plugin bundle. Please try the latest version, and let me know if you still have the same problem.

**Comment by keijiro** [comment] 2018-04-10 08:37
Thanks for clarification.

**Closed by keijiro** 2018-04-10 08:37 UTC
Labels: bug
